name: Dispatch an update to the `service-deploy` repo
on:
  workflow_call:
    inputs:
      service:
        type: string
        required: true
        description: the service whose version should be updated
      version:
        type: string
        required: true
        description: the version string to use
      environment:
        type: string
        required: true
        description: the environment to use

jobs:
  dispatch-service-update:
    name: Dispatch a request to the service-deploy repo to enqueue an update
    runs-on: ubuntu-latest
    steps:
    - uses: benc-uk/workflow-dispatch@e2e5e9a103e331dad343f381a29e654aea3cf8fc
      with:
        workflow: update_deployed_service_file.yml
        inputs: ${{toJson(inputs)}}